language: python
sudo: false

python:
    - 3.5
    - 3.6
    - 3.7-dev

matrix:
  include:
    - python: 3.6
      env:
        - STYLE=1
    - python: 3.6
      env:
        - COVERAGE=1

before_install:
    - python -m pip install --upgrade pip
    - pip install --upgrade virtualenv
    - if [ "${STYLE}" == "1" ]; then
      pip install "flake8<3.0" flake8-putty;
      else
      pip install pytest;
      fi
    - if [ "${COVERAGE}" == "1" ]; then
      pip install coverage coveralls codecov pytest-cov;
      fi

script:
    - |
      if [ "${STYLE}" == "1" ]; then
          flake8 tedana
      else
          if [ "${COVERAGE}" == "1" ]; then
              TEST_ARGS="--cov-report term-missing --cov=tedana";
          else
              TEST_ARGS="";
          fi
          py.test --ignore=tedana/tests/test_tedana.py ${TEST_ARGS} tedana;
      fi

after_success:
    - if [ "${COVERAGE}" == "1" ]; then
          coveralls; codecov;
      fi
